= SAÉ 3.01 devapp G1A-1
:icons: font
:models: models
:experimental:
:incremental:
:numbered:
:toc: macro
:window: _blank
:correction!:

// Useful definitions
:asciidoc: http://www.methods.co.nz/asciidoc[AsciiDoc]
:icongit: icon:git[]
:git: http://git-scm.com/[{icongit}]
:plantuml: https://plantuml.com/fr/[plantUML]
:vscode: https://code.visualstudio.com/[VS Code]

ifndef::env-github[:icons: font]
// Specific to GitHub
ifdef::env-github[]
:correction:
:!toc-title:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
:icongit: Git
endif::[]

// /!\ A MODIFIER !!!
:baseURL: https://github.com/IUT-Blagnac/sae-3-01-devapp-G1A-1

// Tags
image:https://img.shields.io/badge/License-MPL%202.0-brightgreen.svg[License: MPL-2.0, link="https://opensource.org/licenses/MPL-2.0"]
//---------------------------------------------------------------

toc::[]

== Equipe et rôle

Projet réalisé par:

|=== 
| Nom | Rôle 

| https://github.com/HugoTHOLLON[Hugo Thollon] | Scrum master et développeur  
| https://github.com/KilianDemangel[Kilian Demangel] | Développeur  
| https://github.com/RomainGrassaudPicoreau[Romain Grasseau--Picoreau] | Product Owner et développeur  
| https://github.com/ElPoraz[Pablo Marquet] | Développeur  
| https://github.com/titouangauze[Titouan Gauze] | Développeur  
|===


Tuteur enseignant de l'équipe: mailto:jean-michel.bruel@univ-tlse2.fr[Jean-Michel Bruel]

== Contexte général

Le projet a pour objectif de développer une solution e-commerce pour l’entreprise BuildMyPC, spécialisée dans la vente de composants informatiques et d’ordinateurs montés. L’entreprise souhaite élargir son marché en passant d’un modèle B2B à une offre B2C, ciblant les particuliers pour augmenter sa visibilité et sa part de marché en Europe.

== Réalisations 

Cette section regroupe tous les documents liés à la conception, au développement et à l’utilisation de l'application, organisés par catégories principales.

=== Documentation de Conception

Ces documents détaillent les aspects architecturaux et fonctionnels du projet.

- **Document de Conception** : Lien vers le document de conception avec les diagrammes de use case, classe métier, et classe de conception.
  - Lien : link:Documentation/document_conception.adoc[Document de Conception]
- **Diagrammes UML** : Ensemble des diagrammes pour la modélisation de l’application.
  - Lien : link:Documentation/TODO.adoc[SOON - Diagrammes UML]

=== Documentation Technique

Cette section inclut les informations techniques nécessaires pour la compréhension et le développement du projet.

- **Documentation Technique** : Détails de l'architecture, des technologies utilisées, des choix de conception, et des fonctionnalités principales.
  - Lien : link:Documentation/TODO.adoc[SOON - Documentation Technique]
- **Base de Données** : Schéma de la base de données et script de création.
  - Lien : link:Documentation/TODO.adoc[SOON - Base de Données]
  
=== Documentation Utilisateur

Documentation détaillant les fonctionnalités disponibles pour les utilisateurs finaux.

- **Guide Utilisateur** : Instructions pour les clients du site, incluant la création de compte, la gestion du panier, le passage de commandes, et la consultation de l’historique.
  - Lien : link:Documentation/TODO.adoc[SOON - Guide Utilisateur]
- **Guide Administrateur et Employé** : Guide des fonctionnalités accessibles aux administrateurs et employés, telles que la gestion des produits, promotions et utilisateurs.
  - Lien : link:Documentation/TODO.adoc[SOON - Guide Administrateur et Employé]


== Gestion de projet & Qualité

=== Releases

- Version actuelle : https://github.com/IUT-Blagnac/sae3-01-template/releases/tag/v0.1.2[v0.1.2 - SOON V1]

=== Suivi des User Stories

Les User Stories sont disponibles et suivies dans le Project Board GitHub :
https://github.com/IUT-Blagnac/sae-3-01-devapp-G1A-1/projects?query=is%3Aopen[Project Board]

=== Tests et Qualité

Les tests unitaires et les indicateurs de qualité (dette technique) sont accessibles ici :

- Plan de test : link:tests/TODO.adoc[SOON - Disponible ici]

- Indicateurs de qualité : link:tests/TODO.adoc[SOON - résultat des tests et couverture de code via GitHub Actions]

=== Registre de télétravail

- **jeudi 7 novembre**
  * [x] Hugo Thollon, Pablo Marquet, Kilian Demangel, Titouan Gauze
  * [ ] Romain Grasseau--Picoreau

- **jeudi 14 novembre**
  * [x] Pablo Marquet, Kilian Demangel
  * [ ] Romain Grasseau--Picoreau, Hugo Thollon, Titouan Gauze

- **jeudi 20 novembre**
  * [x] Hugo Thollon, Pablo Marquet, Kilian Demangel, Titouan Gauze, Romain Grasseau--Picoreau

== Évaluations hebdomadaires

Evaluation bi-hedomadaire:

ifdef::env-github[]
image:https://docs.google.com/spreadsheets/d/e/2PACX-1vTc3HJJ9iSI4aa2I9a567wX1AUEmgGrQsPl7tHGSAJ_Z-lzWXwYhlhcVIhh5vCJxoxHXYKjSLetP6NS/pubchart?oid=1850914734&amp;format=image[link=https://docs.google.com/spreadsheets/d/e/2PACX-1vTc3HJJ9iSI4aa2I9a567wX1AUEmgGrQsPl7tHGSAJ_Z-lzWXwYhlhcVIhh5vCJxoxHXYKjSLetP6NS/pubchart?oid=1850914734&amp;format=image]
endif::[]

ifndef::env-github[]
++++
<iframe width="786" height="430" seamless frameborder="0" scrolling="no" src="https://docs.google.com/spreadsheets/d/e/2PACX-1vTc3HJJ9iSI4aa2I9a567wX1AUEmgGrQsPl7tHGSAJ_Z-lzWXwYhlhcVIhh5vCJxoxHXYKjSLetP6NS/pubchart?oid=1850914734&amp;format=image"></iframe>
++++
endif::[]
